# Generated by Django 3.0.7 on 2020-06-18 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPartners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название')),
                ('logo', models.FileField(upload_to='delivery_partners', verbose_name='Логотип')),
            ],
            options={
                'verbose_name': 'Партнер доставки',
                'verbose_name_plural': 'Партнеры доставки',
            },
        ),
    ]
