# Generated by Django 3.0.7 on 2020-06-13 20:23

from django.db import migrations, models


def create_online_payment_method(apps, scheme):
    PaymentMethod = apps.get_model('payment', 'PaymentMethod')
    PaymentMethod.objects.create(id=1, name='Оплата онлайн.')


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Способ оплаты',
                'verbose_name_plural': 'Способы оплаты',
            },
        ),
        migrations.RunPython(create_online_payment_method, reverse_code=migrations.RunPython.noop)
    ]
