# Generated by Django 3.0.7 on 2020-06-13 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, verbose_name='Заголовок блока')),
                ('text', models.TextField(default='', verbose_name='Текст блока')),
            ],
            options={
                'verbose_name': 'Блок о нас',
            },
        ),
        migrations.CreateModel(
            name='AboutUsBlockImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='about_us_images/', verbose_name='Изображение')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about_us.AboutUsBlock', verbose_name='Блок')),
            ],
        ),
    ]
