# Generated by Django 3.0.7 on 2020-06-13 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutusblock',
            options={'verbose_name': 'Блок о нас', 'verbose_name_plural': 'Блоки о нас'},
        ),
        migrations.AlterModelOptions(
            name='aboutusblockimage',
            options={'verbose_name': 'Изображение блока', 'verbose_name_plural': 'Изображения блока'},
        ),
        migrations.AlterField(
            model_name='aboutusblock',
            name='text',
            field=models.TextField(blank=True, default='', verbose_name='Текст блока'),
        ),
    ]
