# Generated by Django 2.2.4 on 2019-08-05 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, null=True, verbose_name='Название поста')),
                ('image', models.ImageField(upload_to='blog/', verbose_name='Главное изображение поста')),
                ('likes_number', models.IntegerField(default=0, help_text='Можешь сама накрутить сколько угодно))', verbose_name='Количество лайков')),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
                'ordering': ['-creation_date'],
            },
        ),
        migrations.CreateModel(
            name='PostParagraph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, null=True, verbose_name='Подзаголовок')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('position', models.IntegerField(default=1, verbose_name='Позиция')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paragraphs', to='blog.Post', verbose_name='Пост')),
            ],
            options={
                'verbose_name': 'Параграф',
                'verbose_name_plural': 'Параграфы',
                'ordering': ['position'],
            },
        ),
    ]
