# Generated by Django 2.1.3 on 2018-11-28 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_auto_20181121_0021'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ['position'], 'verbose_name': 'Баннер', 'verbose_name_plural': 'Баннеры'},
        ),
    ]
