# Generated by Django 2.1.3 on 2018-12-02 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_auto_20181128_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageSeoConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SiteMain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='banner',
            name='paragraph',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='tagline',
        ),
    ]
