# Generated by Django 2.2.4 on 2019-08-05 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_auto_20181202_0457'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPaymentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('d', 'Информация о доставке'), ('p', 'Информация об оплате')], max_length=20, null=True, verbose_name='Тип')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок')),
                ('image', models.FileField(blank=True, help_text='В формате svg', null=True, upload_to='delivery/', verbose_name='Иконка')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Информация о доставке и оплате',
                'verbose_name_plural': 'Информация о доставке и оплате',
            },
        ),
        migrations.CreateModel(
            name='Seo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_title', models.CharField(blank=True, max_length=80, null=True, verbose_name='Title')),
                ('index_description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Description')),
                ('index_h1', models.CharField(blank=True, max_length=500, null=True, verbose_name='h1')),
                ('catalog_title', models.CharField(blank=True, max_length=80, null=True, verbose_name='Title')),
                ('catalog_description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Description')),
                ('product_title', models.CharField(blank=True, help_text='Текст появится после названия товара', max_length=80, null=True, verbose_name='Title')),
                ('product_description', models.CharField(blank=True, help_text='Появится после названия товара', max_length=200, null=True, verbose_name='Description')),
                ('delivery_title', models.CharField(blank=True, max_length=80, null=True, verbose_name='Title')),
                ('delivery_description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Description')),
                ('delivery_h1', models.CharField(blank=True, max_length=500, null=True, verbose_name='h1')),
                ('about_title', models.CharField(blank=True, max_length=80, null=True, verbose_name='Title')),
                ('about_description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Description')),
                ('about_h1', models.CharField(blank=True, max_length=500, null=True, verbose_name='h1')),
                ('post_title', models.CharField(blank=True, help_text='Текст появится после названия поста', max_length=80, null=True, verbose_name='Title')),
                ('post_description', models.CharField(blank=True, help_text='Текст появится после названия товара', max_length=200, null=True, verbose_name='Description')),
                ('cart_title', models.CharField(blank=True, max_length=80, null=True, verbose_name='Title')),
                ('cart_description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Description')),
                ('cart_h1', models.CharField(blank=True, max_length=500, null=True, verbose_name='h1')),
            ],
            options={
                'verbose_name': 'Настройки SEO',
                'verbose_name_plural': 'Настройки SEO',
            },
        ),
        migrations.DeleteModel(
            name='PageSeoConfiguration',
        ),
        migrations.AlterModelOptions(
            name='iconspack',
            options={'verbose_name': 'Набор иконок', 'verbose_name_plural': 'Набор иконок'},
        ),
        migrations.AlterModelOptions(
            name='sitemain',
            options={'verbose_name': 'Настройки сайта', 'verbose_name_plural': 'Настройки сайта'},
        ),
        migrations.RemoveField(
            model_name='banner',
            name='image_mini',
        ),
        migrations.RemoveField(
            model_name='iconspack',
            name='navbar_cart',
        ),
        migrations.RemoveField(
            model_name='iconspack',
            name='navbar_instagram',
        ),
        migrations.RemoveField(
            model_name='iconspack',
            name='navbar_vk',
        ),
        migrations.AddField(
            model_name='iconspack',
            name='burger',
            field=models.FileField(blank=True, null=True, upload_to='icons/', verbose_name='Бургер'),
        ),
        migrations.AddField(
            model_name='iconspack',
            name='cart',
            field=models.FileField(blank=True, null=True, upload_to='icons/', verbose_name='Корзина'),
        ),
        migrations.AddField(
            model_name='iconspack',
            name='footer_address',
            field=models.FileField(blank=True, null=True, upload_to='icons/', verbose_name='Адрес(футер)'),
        ),
        migrations.AddField(
            model_name='iconspack',
            name='footer_email',
            field=models.FileField(blank=True, null=True, upload_to='icons/', verbose_name='Email(футер)'),
        ),
        migrations.AddField(
            model_name='iconspack',
            name='footer_phone',
            field=models.FileField(blank=True, null=True, upload_to='icons/', verbose_name='Телефон(футер)'),
        ),
        migrations.AddField(
            model_name='iconspack',
            name='footer_time',
            field=models.FileField(blank=True, null=True, upload_to='icons/', verbose_name='Время работы(футер)'),
        ),
        migrations.AddField(
            model_name='iconspack',
            name='instagram',
            field=models.FileField(blank=True, null=True, upload_to='icons/', verbose_name='Инстаграм'),
        ),
        migrations.AddField(
            model_name='iconspack',
            name='like',
            field=models.FileField(blank=True, null=True, upload_to='icons/', verbose_name='Сердечко(like)'),
        ),
        migrations.AddField(
            model_name='iconspack',
            name='like_white',
            field=models.FileField(blank=True, null=True, upload_to='icons/', verbose_name='Сердечко(белое)'),
        ),
        migrations.AddField(
            model_name='iconspack',
            name='up',
            field=models.FileField(blank=True, null=True, upload_to='icons/', verbose_name='Вверх'),
        ),
        migrations.AddField(
            model_name='iconspack',
            name='vk',
            field=models.FileField(blank=True, null=True, upload_to='icons/', verbose_name='Вконтакте'),
        ),
        migrations.AddField(
            model_name='sitemain',
            name='about_header_image',
            field=models.ImageField(blank=True, null=True, upload_to='header_images/', verbose_name='Изображение страницы о нас'),
        ),
        migrations.AddField(
            model_name='sitemain',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='sitemain',
            name='category_h2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название блока категории'),
        ),
        migrations.AddField(
            model_name='sitemain',
            name='category_par',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Описание блока категории'),
        ),
        migrations.AddField(
            model_name='sitemain',
            name='delivery_header_image',
            field=models.ImageField(blank=True, null=True, upload_to='header_images/', verbose_name='Изображение страницы доставка'),
        ),
        migrations.AddField(
            model_name='sitemain',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Электронный адрес'),
        ),
        migrations.AddField(
            model_name='sitemain',
            name='insta_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на страницу инстаграм'),
        ),
        migrations.AddField(
            model_name='sitemain',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo/', verbose_name='Логотип'),
        ),
        migrations.AddField(
            model_name='sitemain',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AddField(
            model_name='sitemain',
            name='product_h2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название блока продукты'),
        ),
        migrations.AddField(
            model_name='sitemain',
            name='product_par',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Описание блока продукты'),
        ),
        migrations.AddField(
            model_name='sitemain',
            name='sizes_table',
            field=models.ImageField(blank=True, null=True, upload_to='sizes/', verbose_name='Таблица размеров'),
        ),
        migrations.AddField(
            model_name='sitemain',
            name='vk_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на страницу вк'),
        ),
        migrations.AddField(
            model_name='sitemain',
            name='working_hours',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Часы работы'),
        ),
    ]
