# Generated by Django 2.2.4 on 2019-11-15 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_auto_20190805_1933'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IconsPack',
        ),
        migrations.DeleteModel(
            name='Seo',
        ),
    ]
