# Generated by Django 3.0.7 on 2020-06-17 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0008_auto_20200617_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitemain',
            name='organisation_line1',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Организация(строка 1)'),
        ),
        migrations.AlterField(
            model_name='sitemain',
            name='organisation_line2',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Организация(строка 2)'),
        ),
        migrations.AlterField(
            model_name='sitemain',
            name='organisation_line3',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Организация(строка 3)'),
        ),
        migrations.AlterField(
            model_name='sitemain',
            name='organisation_line4',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Организация(строка 4)'),
        ),
    ]
