# Generated by Django 3.0.7 on 2020-06-17 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0009_auto_20200617_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=False, verbose_name='Доступна')),
                ('link', models.CharField(default='', max_length=250, verbose_name='Ссылка или номер')),
            ],
        ),
        migrations.AlterField(
            model_name='sitemain',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Адрес (через запятую)'),
        ),
    ]
