# Generated by Django 3.0.7 on 2020-06-17 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0010_auto_20200617_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitemain',
            name='insta_url',
        ),
        migrations.RemoveField(
            model_name='sitemain',
            name='vk_url',
        ),
    ]
