# Generated by Django 3.0.7 on 2020-06-18 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0011_auto_20200617_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallink',
            name='link',
            field=models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='Ссылка или номер'),
        ),
    ]
