# Generated by Django 3.0.7 on 2020-06-21 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0014_auto_20200618_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitemain',
            name='phone_number',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Номер телефона'),
        ),
    ]
