# Generated by Django 2.1.3 on 2018-11-15 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display', models.BooleanField(default=True, verbose_name='Отображается')),
                ('name', models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='Название')),
                ('price_no_sale', models.PositiveSmallIntegerField(default=0, verbose_name='Цена(без скидки)')),
                ('price_sale', models.PositiveSmallIntegerField(default=0, verbose_name='Цена(со скидкой)')),
                ('material', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Состав')),
                ('models_height', models.PositiveSmallIntegerField(default=165, verbose_name='Рост модели')),
                ('description', models.TextField(default='', verbose_name='Описание товара')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=300, verbose_name='Категория товаров')),
                ('image', models.ImageField(upload_to='categories/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_full', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Изображение')),
                ('image_mini', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Изображение(миниатюра)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', related_query_name='images', to='shop.Product')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=300, verbose_name='Размер')),
            ],
            options={
                'verbose_name': 'Размер',
                'verbose_name_plural': 'Размеры',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.ProductCategory', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.ManyToManyField(related_name='sizes', related_query_name='sizes', to='shop.ProductSize', verbose_name='Размеры'),
        ),
    ]
