# Generated by Django 2.2.4 on 2019-08-05 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processed', models.BooleanField(default=False, verbose_name='Перезвонили')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Имя')),
                ('phone', models.CharField(blank=True, max_length=200, null=True, verbose_name='Номер Телефона')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания заявки')),
            ],
            options={
                'verbose_name': 'Заявка связаться с нами',
                'verbose_name_plural': 'Заявки связаться с нами',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processed', models.BooleanField(default=False, verbose_name='Обработан')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('customer', models.CharField(default='', max_length=200, verbose_name='Покупатель')),
                ('phone_number', models.CharField(default='', max_length=20, verbose_name='Номер телефона')),
                ('total', models.PositiveIntegerField(default=0, verbose_name='Сумма заказа')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-date'],
            },
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['id'], 'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_no_sale',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_sale',
        ),
        migrations.AddField(
            model_name='product',
            name='prev_price',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='Цена без скидки'),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Цена'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(to='shop.ProductCategory', verbose_name='Категории'),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=300, verbose_name='Название')),
                ('size', models.CharField(default='', max_length=50, verbose_name='Размер')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Цена')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Количество')),
                ('subtotal', models.PositiveIntegerField(default=0, verbose_name='Сумма')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Order', verbose_name='Заказ')),
            ],
        ),
    ]
