# Generated by Django 2.2.4 on 2019-11-15 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20190805_1933'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ('id',), 'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
    ]
