# Generated by Django 3.0.7 on 2020-06-12 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20200611_1321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='image_full',
            new_name='file',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='image_mini',
        ),
    ]
