# Generated by Django 3.0.7 on 2020-06-13 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20200612_1507'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactPerson',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
