# Generated by Django 2.2.4 on 2019-11-15 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0003_auto_20191115_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='SitePageSeo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Данный текст будет идти после названия продукта: Например, Юбка - текст title', max_length=750, null=True, verbose_name='Title')),
                ('description', models.CharField(blank=True, help_text='Данный текст будет идти после названия продукта: Например, Юбка - текст description', max_length=1000, null=True, verbose_name='Description')),
                ('keywords', models.CharField(blank=True, max_length=750, null=True, verbose_name='Keywords')),
                ('additional_html', models.TextField(blank=True, help_text='Дополнительные теги будут в блоке head на странике товара', null=True, verbose_name='Дополнительное')),
                ('page_name', models.CharField(max_length=250, verbose_name='Название страницы')),
            ],
            options={
                'verbose_name': 'Seo страницы',
                'verbose_name_plural': 'Seo страниц сайта',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductPageSeo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Данный текст будет идти после названия продукта: Например, Юбка - текст title', max_length=750, null=True, verbose_name='Title')),
                ('description', models.CharField(blank=True, help_text='Данный текст будет идти после названия продукта: Например, Юбка - текст description', max_length=1000, null=True, verbose_name='Description')),
                ('keywords', models.CharField(blank=True, max_length=750, null=True, verbose_name='Keywords')),
                ('additional_html', models.TextField(blank=True, help_text='Дополнительные теги будут в блоке head на странике товара', null=True, verbose_name='Дополнительное')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='page_seo', to='shop.Product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Seo страницы товара',
                'verbose_name_plural': 'Seo страниц товаров',
            },
        ),
    ]
