# Generated by Django 3.0.7 on 2020-06-17 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitepageseo',
            name='h1',
            field=models.CharField(default='', max_length=500, verbose_name='H1'),
            preserve_default=False,
        ),
    ]
