# Generated by Django 3.0.7 on 2020-06-17 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0002_sitepageseo_h1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitepageseo',
            name='h1',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='H1'),
        ),
    ]
