# Generated by Django 3.0.7 on 2020-06-15 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('delivery', '0001_initial'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_connect', models.BooleanField(blank=True, default=False, verbose_name='Без обратной связи')),
                ('connect_by_phone', models.BooleanField(blank=True, default=False, verbose_name='Связаться по телефону')),
                ('connect_by_whatsapp', models.BooleanField(blank=True, default=False, verbose_name='Связаться по whatsapp')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Комментарий покупателя')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='OrderPersonalInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250, verbose_name='Имя')),
                ('second_name', models.CharField(max_length=250, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=250, verbose_name='Электронная почта')),
                ('phone_number', models.CharField(max_length=250, verbose_name='Номер телефона')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personal_info', to='order.Order', verbose_name='Заказ')),
            ],
        ),
        migrations.CreateModel(
            name='OrderPaymentInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payed', models.BooleanField(default=False, verbose_name='Оплатчено')),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.PaymentMethod', verbose_name='Метод оплаты')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.PositiveIntegerField(default=1)),
                ('product_name', models.CharField(max_length=1000, verbose_name='Название продукта')),
                ('size', models.CharField(max_length=50, verbose_name='Размер')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Цена')),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('order', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.Order', verbose_name='Заказ')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDeliveryInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(max_length=10, verbose_name='Индекс')),
                ('city', models.CharField(max_length=500, verbose_name='Населенный пункт (город)')),
                ('street', models.CharField(max_length=500, verbose_name='Улица')),
                ('building_number', models.CharField(max_length=20, verbose_name='Номер дома')),
                ('apartment', models.CharField(max_length=20, verbose_name='Квартира')),
                ('delivery_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='delivery.DeliveryMethod', verbose_name='Метод доставки')),
            ],
        ),
    ]
