# Generated by Django 3.0.7 on 2020-06-16 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdeliveryinformation',
            name='apartment',
            field=models.CharField(default='', max_length=20, verbose_name='Квартира'),
        ),
        migrations.AlterField(
            model_name='orderdeliveryinformation',
            name='building_number',
            field=models.CharField(default='', max_length=20, verbose_name='Номер дома'),
        ),
        migrations.AlterField(
            model_name='orderdeliveryinformation',
            name='city',
            field=models.CharField(default='', max_length=500, verbose_name='Населенный пункт (город)'),
        ),
        migrations.AlterField(
            model_name='orderdeliveryinformation',
            name='index',
            field=models.CharField(default='', max_length=10, verbose_name='Индекс'),
        ),
        migrations.AlterField(
            model_name='orderdeliveryinformation',
            name='street',
            field=models.CharField(default='', max_length=500, verbose_name='Улица'),
        ),
        migrations.AlterField(
            model_name='orderpersonalinformation',
            name='email',
            field=models.EmailField(default='', max_length=250, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='orderpersonalinformation',
            name='first_name',
            field=models.CharField(default='', max_length=250, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='orderpersonalinformation',
            name='phone_number',
            field=models.CharField(default='', max_length=250, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='orderpersonalinformation',
            name='second_name',
            field=models.CharField(default='', max_length=250, verbose_name='Фамилия'),
        ),
    ]
