# Generated by Django 3.0.7 on 2020-06-16 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20200616_0336'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdeliveryinformation',
            name='order',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='order.Order'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderpaymentinformation',
            name='order',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='order.Order'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderpaymentinformation',
            name='payed',
            field=models.BooleanField(default=False, verbose_name='Оплачено'),
        ),
    ]
