# Generated by Django 3.0.7 on 2020-06-16 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20200616_0338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderpaymentinformation',
            name='payed',
        ),
    ]
