# Generated by Django 3.0.7 on 2020-06-16 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_remove_orderpaymentinformation_payed'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='fast_buy',
            field=models.BooleanField(default=False, verbose_name='В 1 клик'),
        ),
    ]
